install:
  clustermon: true
  defaultInfraCollectors: true
  logCollector: false

mTLS:
  enabled: true
  client:
    secretName: ""
    secretKeys:
      caCert: ca.crt
      tlsCert: tls.crt
      tlsKey: tls.key
  server:
    secretName: ""
    secretKeys:
      caCert: ca.crt
      tlsCert: tls.crt
      tlsKey: tls.key

# RBAC config
clustermonServiceAccount: appdynamics-clustermon
inframonServiceAccount: appdynamics-inframon
otelCollectorServiceAccount: appdynamics-otel-collector
logCollectorServiceAccount: appdynamics-log-collector

# Clustermon Configs
clustermonConfig:
  clusterName: null
  logLevel: info
  logFilesMaxSizeMb: 10
  logFilesNumBackups: 4
  printToStdout: "true"

  filters:
    namespace:
      includeRegex: ".*"
      excludeRegex: ""
    entity:
      excludeRegex: ""
      excludeLabels: []
    label:
      excludeRegex: ""

  ingressControllers: {}

  events:
    enabled: true
    severityToExclude: [Normal]
    reasonToExclude: []
    severeGroupByReason: []

# Infra Manager Configs
infraManagerConfig:
  logLevel: info
  logFilesMaxSizeMb: 10
  logFilesNumBackups: 4
  printToStdout: "true"

# Servermon Configs
servermonConfig:
  logLevel: info
  logFilesMaxSizeMb: 10
  logFilesNumBackups: 4

# Containermon Configs
containermonConfig:
  logLevel: info
  logFilesMaxSizeMb: 10
  logFilesNumBackups: 4

# LogCollector Configs
logCollectorConfig:
  container:
    conditions:
      - condition: {}
        multiLinePattern:
        multiLineNegate:
        multiLineMatch:
        messageParserLog4JPattern:
        messageParserLogbackPattern:
        enableJSONLogs:
        jsonTimestampField:
        jsonTimestampPattern:
        messageParserTimestampFormat:
        messageParserGrokPatterns:
        grokTimestampField:
        grokTimestampPattern:
        enableInfraLogs:
    clusterName:
    batchSize:
    loggingLevel:
    loggingSelectors: []
    monitoringEnabled:
    monitoringLoggingPeriod:
  filebeatYaml: ""

# Deployment specific configs
clustermonPod:
  image: public.ecr.aws/appdynamics-container-registry/appdynamics-cloud-k8s-monitoring:22.5.0
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 750Mi
  labels: {}
  annotations: {}
  nodeSelector: {}
  imagePullSecrets: []
  affinity: {}
  tolerations: []
  securityContext: {}

# Daemonset specific configs
inframonPod:
  image: public.ecr.aws/appdynamics-container-registry/appdynamics-cloud-k8s-monitoring:22.5.0
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 350m
      memory: 100Mi
    requests:
      cpu: 200m
      memory: 64Mi
  labels: {}
  annotations: {}
  nodeSelector: {}
  imagePullSecrets: []
  affinity: {}
  tolerations: []
  securityContext: {}

# Daemonset specific configs
otelCollectorPod:
  image: public.ecr.aws/appdynamics-container-registry/appdynamics-otel-collector:22.1.0
  imagePullPolicy: Always
  env: []
  resources:
    limits:
      cpu: 400m
      memory: 300Mi
    requests:
      cpu: 200m
      memory: 150Mi
  labels: {}
  annotations: {}
  nodeSelector: {}
  imagePullSecrets: []
  affinity: {}
  tolerations: []
  securityContext: {}

# Daemonset specific configs
logCollectorPod:
  image: public.ecr.aws/appdynamics-container-registry/appdynamics-beats:22.4.0
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 400m
      memory: 300Mi
    requests:
      cpu: 200m
      memory: 150Mi
  labels: {}
  annotations: {}
  nodeSelector: {}
  imagePullSecrets: []
  affinity: {}
  tolerations: []
  securityContext: {}

otelCollector:
  config:
    oauth2client:
      clientId: ""
      clientSecret: ""
      tenantId: ""
    endpoint: ""
    logLevel: "info"
  configOverride: ""
